# Generated by Django 4.2.7 on 2023-11-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositoptions',
            name='intr_rate_type',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='depositproducts',
            name='dcls_end_day',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='depositproducts',
            name='dcls_month',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='depositproducts',
            name='fin_co_no',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='depositproducts',
            name='fin_co_subm_day',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='depositproducts',
            name='max_limit',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='depositproducts',
            name='mtrt_int',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='savingproducts',
            name='dcls_end_day',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='savingproducts',
            name='dcls_month',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='savingproducts',
            name='dcls_strt_daymit',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='savingproducts',
            name='fin_co_no',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='savingproducts',
            name='fin_co_subm_day',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='savingproducts',
            name='max_limit',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='savingproducts',
            name='mtrt_int',
            field=models.TextField(null=True),
        ),
    ]
