# Generated by Django 4.2.7 on 2023-11-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_alter_depositoptions_intr_rate_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositproducts',
            name='dcls_strt_daymit',
            field=models.TextField(null=True),
        ),
    ]
