# Generated by Django 4.2.4 on 2023-11-20 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='finance',
        ),
        migrations.AddField(
            model_name='comments',
            name='QnA',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='QnA_comments', to='boards.questionanswers'),
        ),
        migrations.DeleteModel(
            name='FinanceReviews',
        ),
    ]
